<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release</Configurations>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\bin\Debug-windows-x86_64\VeloraServer\</OutputPath>
    <IntermediateOutputPath>..\bin-int\Debug-windows-x86_64\VeloraServer\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>..\bin\Release-windows-x86_64\VeloraServer\</OutputPath>
    <IntermediateOutputPath>..\bin-int\Release-windows-x86_64\VeloraServer\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Src\Configuration\ServerConfig.cs" />
    <Compile Include="Src\Models\NetworkMessages.cs" />
    <Compile Include="Src\Models\Player.cs" />
    <Compile Include="Src\Program.cs" />
    <Compile Include="Src\Server.cs" />
    <Compile Include="Src\Services\ClientConnection.cs" />
    <Compile Include="Src\Services\NetworkManager.cs" />
    <Compile Include="Src\Services\PlayerManager.cs" />
    <Compile Include="Src\Utils\Log.cs" />
    <None Include="VeloraServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="3.1.1"/>
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0"/>
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0"/>
  </ItemGroup>
</Project>